# Site settings
title: Brian Manning
email: manningbrian98@gmail.com
url: https://github.com/manningb/
description: "Hello! My name is Brian Manning, I'm a 22 year old Freelance Web Developer from Kilkenny currently studying an Msc in Computer Science in UCD. I have a wide range of experience including getting websites setup from scratch along with maintaining and analysing them."
keywords: "web developer, computer science, ireland, dublin, kilkenny, python, wordpress"
skills: "Web Developer - Current Msc Computer Science - Bsc Actuarial Science"
meta_author: Manning Brian

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static
email: meqpzvbg
# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Brian Manning
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
        # - title: twitter
        #  url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/manningbrian98/
    #- title: stack-overflow
    # url: http://stackoverflow.com/questions/tagged/jekyll
    # - title: bitbucket
    # url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/manningb
  - title: linkedin
    url: https://www.linkedin.com/in/manning-brian/

# Postal address (add as many lines as necessary)
address:
  - line: Kilkenny/Dublin
  - line: Ireland

# Credits content
credits: 'Thank you for visiting my website!'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
