# File: .github/workflows/refresh.yml
name: Refresh

on:
  schedule:
    - cron:  '10 * * * *' # Runs every day at 3am

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/manningb.github.com/pages/builds \
            --header "Authorization: Bearer c03fa7b61fd654b76010a85c9093cbdcf185599d"
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: c03fa7b61fd654b76010a85c9093cbdcf185599d
